print(' ------------------------------------------------ ')
print('|                                                |')
print('|    03HelloWorld                                |')
print('|    Name : Alicia R                             |')
print('|    Version : 01                                |')
print('|                                                |')
print(' ------------------------------------------------ ')
print('Hello World')
x = input('What is your name ? ')
print('Goodbye ' + x)
