print(' ------------------------------------------------ ')
print('|                                                |')
print('|    03GoodbyePerson                             |')
print('|    Name : Alicia R                             |')
print('|    Version : 01                                |')
print('|                                                |')
print(' ------------------------------------------------ ')
print('Hello')
x = input('What is your name ? ')
print('Goodbye ' + x)

