print(' ------------------------------------------------ ')
print('|                                                |')
print('|    04GoodTeacher                               |')
print('|    Name : Alicia Rodrigues                     |')
print('|    Version : 01                                |')
print('|                                                |')
print(' ------------------------------------------------ ')
print('Hello World')